### ISSUE TITLE
signInWithOtp does not honour emailRedirectTo

### ISSUE THREAD

**Issue by ak4zh** [supabase/gotrue-js#418]
# Bug report

emailRedirectTo option is ignored in signInWithOtp
```js
await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo:  "https://example.com" } });
```

I have tried setting following urls in the Dashboard > Authentication > Settings

- Attempt 1:
  - Site URL = `https://example.com`
  - Redirect URLs = `https://example.com, https://example.com/*`

- Attempt 2:
  - Site URL = `https://example.com/**`
  - Redirect URLs = `https://example.com, https://example.com/*`

The Magic link still contains the local URL `&type=magiclink&redirect_to=http://127.0.0.1:5173` 

## System information

- Version of supabase-js: 2.0.0-rc.7

**Comment by ak4zh** [comment]
On further inspection, I noticed this problem only occurs if the `supabase.auth.signInWithOtp` is run server side and not in client.
Seems to work fine if run client-side.

**Comment by ak4zh** [comment]
Finally I have got it solved with following configs.

```
Supabase Dashboard > Authenticaltion > User session > Site URL = https://example.com
Allowed redirec domains = https://example.com/**
```

Supabase-js 
```js
await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo:  "https://example.com/login" } });
```

**Comment by arshamg** [comment]
I am having the same issue. I cannot get this to work for multiple domains.

**Comment by Samesh** [comment]
I'm using the same function on client but it still doesn't seem to work for me.

`const { error } = await supabase.auth.signInWithOtp(
                {
                email: userData.email,
                options: {
                    emailRedirectTo: `${process.env.NEXT_PUBLIC_WEBSITE_URL}/home/explore`
                }
            })
`

"@supabase/supabase-js": "^2.0.2",

**Comment by troyshu** [comment]
> Finally I have got it solved with following configs.
> 
> ```
> Supabase Dashboard > Authentication > User session > Site URL = https://example.com
> Allowed redirec domains = https://example.com/**
> ```
> 
> Supabase-js
> 
> ```js
> await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo:  "https://example.com/login" } });
> ```

@arshamg @Samesh did you try @ak4zh's suggestion above? Adding `https://example.com/**` to the redirect domains in the dashboard (when `emailRedirectTo` is something like  `"https://example.com/login"`) fixed it for me too.

**Comment by Samesh** [comment]
@troyshu thanks for following up. It worked for me. I'm using next auth helpers and I had configured my redirect route to push back to the landing page if no user is present. The redirect from the link actually works when I turn it off. I ended up creating an auth loader page which redirects to the home page once a user was signed in. Hope that was clear. Thanks

**Comment by Ddupasquier** [comment]
I'm having the same issue. I tried what @ak4zh did, but either I'm misunderstanding OR it's just not working.
When I try to login from vercel deployed, it obviously works. But when I try to login via local host, I'm just redirected to vercel site.

Client: 
```js
<script lang="ts">
	import { supabase } from '$lib/supabase';

	let loading = false;
	let email = '';

	const handleLogin = async () => {
		const isLocalhost = () => {
			let local;
			if (window.location.hostname === 'localhost') local = 'http://localhost:5173/';
			else local = 'https://stories-client.vercel.app/';
			return local;
		};

		try {
			loading = true;
			const { error } = await supabase.auth.signInWithOtp({
				email,
				options: {
					emailRedirectTo: isLocalhost(),
				}
			});

			if (error) throw error;
			alert('Check your email for login link!');
		} catch (error) {
			if (error instanceof Error) {
				alert(error.message);
			}
		} finally {
			loading = false;
		}
	};
</script>
```

![image](https://user-images.githubusercontent.com/89223122/211132789-6e4a27d1-5e5d-4284-8260-d4ccd5f7372e.png)

**Comment by arshamg** [comment]
Try:
`https://localhost:5173` no trailing `/`

**Comment by Ddupasquier** [comment]
> Try:
> `https://localhost:5173` no trailing `/`

I did. No success :/

**Comment by troyshu** [comment]
Some weekend warriors here!

> > Try:
> > `https://localhost:5173` no trailing `/`
> 
> I did. No success :/

Try setting the redirect URL to `http://localhost:5173` (no `s` after `http`, no trailing slash). Then in your code, the try the redirect URL as  'http://localhost:5173' (not trailing slash). Basically, it seems like your redirect URL(s) in the supabase dashboard don't match the redirect URL you're giving supabase in your code.

**Comment by Ddupasquier** [comment]
> Some weekend warriors here!
> 
> > > Try:
> > > `https://localhost:5173` no trailing `/`
> > 
> > I did. No success :/
> 
> Try setting the redirect URL to `http://localhost:5173` (no `s` after `http`, no trailing slash). Then in your code, the try the redirect URL as  'http://localhost:5173' (no trailing slash). Basically, it seems like your redirect URL(s) in the supabase dashboard don't match the redirect URL you're giving supabase in your code.

Oh, you're totally right! I'll give that a shot!

Progress:
I get a redirect to local host but I get an ERR_SSR_PROTOCOL_ERROR
Local host sent invalid response.
Is this still something in the supabase stuff, or did I mess up my code?

**Comment by wiesson** [comment]
@Ddupasquier - did you solve that? I remember that it used to work, but with a fresh project I'm not able to get it right 🤷‍♂️ 

I tried to add 

```
http://localhost:5173/** // should work, according to the docs
http://localhost:5173/*
http://localhost:5173**
http://localhost:5173*
http://localhost:5173/auth/confirm // exact path that I'm using for SSR
```

but I still endup with receiving the main Domain 😢

**Comment by lyonsbp** [comment]
> @Ddupasquier - did you solve that? I remember that it used to work, but with a fresh project I'm not able to get it right 🤷‍♂️
> 
> I tried to add
> 
> ```
> http://localhost:5173/** // should work, according to the docs
> http://localhost:5173/*
> http://localhost:5173**
> http://localhost:5173*
> http://localhost:5173/auth/confirm // exact path that I'm using for SSR
> ```
> 
> but I still endup with receiving the main Domain 😢

Im having this same issue with a remix app. `emailRedirectTo` is NOT respecting my `http://localhost:8788` url I am passing. Did you ever figure this out?

**Comment by luzhenqian** [comment]
> > @Ddupasquier - did you solve that? I remember that it used to work, but with a fresh project I'm not able to get it right 🤷‍♂️
> > I tried to add
> > ```
> > http://localhost:5173/** // should work, according to the docs
> > http://localhost:5173/*
> > http://localhost:5173**
> > http://localhost:5173*
> > http://localhost:5173/auth/confirm // exact path that I'm using for SSR
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but I still endup with receiving the main Domain 😢
> 
> Im having this same issue with a remix app. `emailRedirectTo` is NOT respecting my `http://localhost:8788` url I am passing. Did you ever figure this out?

I tried all the configurations like you and still can't work.

But I found another way to solve this problem.

Write the following code at the entrance of Next.js 14:

```ts
import { redirect } from "next/navigation";

export default function RootPage({ searchParams }: any) {
  // process supabase auth redirect
  const code = searchParams?.code;
  if (code) {
    return redirect(`/auth/callback?code=${code}`);
  }
  
  // Your logic
}
```

Note that this is a server-side component.

While probably not best practice, it works.

You can try it.

**Comment by djshubs** [comment]
I am here to also say that the `emailRedirectTo` using the new @supabase/ssr always returns the origin. I am using the exact code from their [documentation](https://supabase.com/docs/guides/auth/server-side/nextjs?router=app) for `auth/confirm` route which uses 'next' search params. 

My email template has the following url: `{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&type=email&next={{ .RedirectTo }}` 

This resolves to `http://localhost:3000/` even though I set the `emailRedirectTo=/admin` in the `signInWithOtp` function.

What's confusing is the code in the documentation makes it seem that redirectTo should be a path, however it always resolves to a full url. 

I am running Supabase locally and have updated to the latest version of docker images.

cc @kangmingtay and [#1271](https://github.com/supabase/gotrue/issues/1271)

**Comment by joshdance** [comment]
@djshubs did you get /ssr to work? I am having similar issues.

**Comment by djshubs** [comment]
I did but I am having to use the full callback url and then parse the `redirect_to=` from the `request.url` in my route handler and get to the `next` search parameter.  


The URL getting generated for me usually is:

`example.com/auth/callback?tokenHash={hash}&redirect_to=example.com/auth/callback?next=/account`. 

Let me know or if this makes sense.

**Comment by adamkdean** [comment]
I also having this issue. `signInWithOtp` doesn't seem to be honouring any of the options.

**Comment by lucasschakel** [comment]
Same, also got issues with `emailRedirectTo` not working. Followed the exact ssr auth guide: https://supabase.com/docs/guides/auth/server-side/nextjs

**Comment by ordinz** [comment]
Setting up these redirect urls worked for me, thank you!

https://*.mydomain.com/**
http://localhost:3000/**

**Comment by adamcohenhillel** [comment]
This is still an open issue on my end. Deployed on Vercel completely ignores `emailRedirectTo` in `signInWithOtp` and `redirectTo` in `signInWithOAuth`.

It does work on localhost.

**Comment by Xufysz** [comment]
I spent hours on this today. If you have created a new NextJS app with Supabase, in **local development** inside supabase/config.toml the site_url will default to http://127.0.0.1. 

It's also worth noting, when changing this, you must restart your local supabase docker instance (npx supabase stop & npx supabase start) for any changes to take effect. 

My config now looks like:
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]

and I can now use http://localhost:3000/auth/callback as a redirectUrl for OTP.

**Comment by naz** [comment]
@kangmingtay is the above an intentional behavior?

**Comment by JigBack** [comment]
Has anyone had any luck solving this issue?

My `config.toml` has the following:

`site_url = "http://localhost:3000"`
`additional_redirect_urls = ["http://localhost:3000/**"]`

I've tried everything suggested so far in this thread and still the email being sent contains this link:

`http://127.0.0.1:54321/auth/v1/verify?token=***&type=magiclink&redirect_to=http://localhost:3000`
