### ISSUE TITLE
supabase.auth.getSession() doesn't work after a successful SAML 2.0 login

### ISSUE THREAD

**Issue by dilly-sixmo** [supabase/gotrue-js#768]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

**TLDR**: Some version between `2.24.0` and `2.45.0` of `@supabase/gotrue-js` has made the `supabase.auth.getSession()` not work after successfully authenticating with an SAML 2.0 provider (Azure in this case).  It never seems to resolve.

I recently updated all the dependencies for my project with `ncu -u`.  Everything looked to be going great so I pushed forward and also reset my supabase DB during this timeframe.  At some point, I logged out and I was unable to log back in.  I wasn't sure what the problem was but initially I thought it was something to do with me resetting the supabase DB.  I checked everything in my code, my Azure configuration, my Supabase configuration, and everything seemed fine.  Then I decided to go back to a previous commit before the dependency update, and I could see that it was working again. So I knew it was some dependency, and not any server configuration that was causing this.

After some troubleshooting, I was able to narrow it down to the `@supabase/gotrue-js` library.  When I use version `2.24.0`, it all works fine, and `supabase.auth.getSession()` returns what I'd expect.  But when I use `2.45.0`, `supabase.auth.getSession()` never returns a thing.  It's just broken.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a Supabase project with SAML 2.0 as an Auth Provider and get it configured
2. Use the `supabase.auth.signInWithSSO()` method, providing it with a `domain` and `redirectUrl`
3. `supabase.auth.signInWithSSO()` will reply with a `data.url`.  Redirect the user to this URL for authentication
4. The user logs in via the SAML Identity Provider (Azure in this case), and upon successful authentication the user is redirected to the specified `redirectUrl`
5. When the user returns to the app at the `redirectUrl`, use `supabase.auth.getSession()` to retrieve the user's session
6. `supabase.auth.getSession()` never returns anything and is broken

## Expected behavior

`supabase.auth.getSession()` should return something, not hang forever.  Specifically, it should return an object with a `session` property.  This `session` property should be an object that contains an `access_token`, a `user` object, among other properties.

**Comment by hf** [comment]
Just so you're aware, there was a lot of churn on `supabase.auth.getSession()` for a while in a few versions. This is why it's super important to make sure to keep up to date with the latest version, and report issues promptly.

I'll be closing this now.

**Comment by thorleifjacobsen** [comment]
Not sure related. I've updated to the latest version And I see this problem now. It seems to do nothing? Any idea?

![image](https://github.com/supabase/gotrue-js/assets/8550684/1ea42dab-7d56-46d0-8097-59678169e8d0)
![image](https://github.com/supabase/gotrue-js/assets/8550684/1925c3bf-a64d-4bb4-b70e-eabf33ad3afd)

**Comment by GraysonQuartech** [comment]
this is currently an issue for me... much later versions that mentioned above^

**Comment by nbarrow-inspire-labs** [comment]
+1 I am also seeing this happening again: 
```json
{
  "dependencies": {
    "@supabase/supabase-js": "^2.39.6"
  }
}
```

**Comment by Andriiklymiuk** [comment]
same error, why it is closed? 
2.39.8 version

**Comment by 14790897** [comment]
I fixed the issue by reinstalling all the packages

**Comment by samhiggs** [comment]
Same issue  with 2.49.3
calling getSession() after logging in causes it to hang infinitely.

**Comment by monoskin** [comment]
@samhiggs Were you able to find a solution?

**Comment by ericgaooo** [comment]
I am also having the same problem ^^^ 

it's really strange. getSession() will hang after I open my app for the first time in a while, and then if i close and reopen my app it'll return successfully right away.

**Comment by DPLucent** [comment]
I am also having the same issue, getSession() hangs indefinitely

**Comment by ningt** [comment]
I am having the same issue with `"@supabase/supabase-js": "^2.49.4"`

**Comment by writeriks** [comment]
i have the same issue. 

I thought it is related to https://github.com/supabase/supabase-js/issues/1400

But even with the supabase update i have `supabase.auth.getSession()` does not get resolved.

Below are the packages i am using

```
"@supabase/gotrue-js": "^2.69.1",
"@supabase/supabase-js": "^2.49.5-next.1",
```

**Comment by DPLucent** [comment]
yup - still having the same issue with "@supabase/supabase-js": "^2.49.4" it is very frustrating & causing users to not be able to login, anyone know what I can do?

**Comment by Enes-Kayiklik** [comment]
I tried every combination including Pre release ones but there is only fix is setting the `"@supabase/supabase-js": "2.30.0"` or `"@supabase/supabase-js"`: `"2.29.0"`.  When i upgrade to any version greater than `2.30.0` the issue is came back. Only change from `2.30.0` to `2.31.0` is `gotrue-js` version.

**Comment by FredySandoval** [comment]
in my case, I was building with `pnpm` but I switch to `npm` and the issue was fixed

**Comment by sgraphics** [comment]
Same issue still in latest version, getSession just hangs, never finishes. Also getUser from gotrue-js is giving 401 fetch errors randomly. About 10% of the time. Very annoying.

**Comment by nagmak** [comment]
I'm on `@supabase/supabase-js": "^2.50.2",` and running into the same issue

**Comment by sgraphics** [comment]
I found the issue is actually dead-lock. There's a separate paragraph in docs about it https://supabase.com/docs/reference/javascript/auth-onauthstatechange

_Important: A callback can be an async function and it runs synchronously during the processing of the changes causing the event. You can easily create a dead-lock by using await on a call to another method of the Supabase library._

Follow the detailed instructions there. Unfortunately AI does not follow these instructions which is when you run into the issue.

**Comment by APTy** [comment]
It's definitely a deadlock, workaround is in supabase/supabase-js#1594
